#!/usr/bin/ruby
# coding: utf-8
# vim: noai:ts=4:sw=4
#
#  Copyright (C) 2010-2017 by Luiz Angelo Daros de Luca
#    luizluca@gmail.com
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    Created on 2010-08-10
#
# Changelog:
#
# * 2017-03-17
# - Add support for http proxy authentication using auto-detect support
#
# * 2010-09-01
# - Add TCP keepalive flags for local socket (thanks Jan Adámek)
# - Increased local buffer to 640k
# - Fixed sync problem with stdin/out when using as ProxyCommand inside ssh config
# - Reconnection on client-webrick disconnection
# - Fixed proxy absence
# - Specified webrick timeout (10m)
# - Treated more signals
# - Divide connection (open, read, write)
#
#
#################
#
# Port Forward client/server over HTTP
#
#################

class String
    def strip_heredoc
        min = scan(/^[ \t]*(?=\S)/).min
        if min == nil
            indent=0
        else
            indent=min.size
        end
        gsub(/^[ \t]{#{indent}}/, '')
    end
end

case ARGV.size
    when 2
        server=true
        location=ARGV[1]
     when 4
        server=false
        url=ARGV[1]
        remote_host=ARGV[2]
        remote_host=remote_host.gsub(/^bprox\d+_/,'')
        remote_port=ARGV[3].to_i
    else
    $stderr.puts <<-EOF.strip_heredoc
	Use as server:
	#$0 localPort bridgeLocation
	
	Use as client:
	#$0 localPort|STDIN bridgeURL remoteAddress remotePort
	
	Ex:
	bridge$ #$0 8080 /bridge
	
	client$ #$0 8022 http://mybridge:8080/bridge remoteServer 22
	client$ ssh localhost -p 8022
	EOF
    exit
end

localPort=ARGV[0]

require 'socket'
require 'thread'
Thread.abort_on_exception = true

MAXBUF=1024*640 # 640k
READ_TIMEOUT=60
SERVER_CONNECTION_TIMEOUT=60*60*10 # 10 hours
CLIENT_MAX_CONNECTIONS=32
CLIENT_PENDING_CONNECTIONS=6
if server
    require 'webrick'

    class BridgeServlet < WEBrick::HTTPServlet::AbstractServlet
        @@connections = {}

        def get_socket(req,res)
            conn_id = req.path.split("/").last
            if not @@connections.has_key? conn_id
                $stderr.puts "[#{conn_id}] Connection is not open for #{conn_id}"
                res.status=404 # Not Found
                return nil
            end
            @@connections[conn_id][0]=Time.now
            @@connections[conn_id][1]
        end

        def close_socket(req,res)
            conn_id = req.path.split("/").last
            return if not @@connections.has_key? conn_id
            @@connections[conn_id][1].close if not @@connections[conn_id][1].closed?
            @@connections.delete(conn_id)
        end

        def do_POST(req, res)
            conn_id = req.path.split("/").last
            (remote_host,colon,remote_port)=req.body.rpartition(":")
            remote_port=remote_port.to_i
            $stderr.puts "[#{conn_id}] Opening connection to #{remote_host}:#{remote_port} for #{req.peeraddr}..."
            begin
                if not @@connections.has_key? conn_id
                    conn=[Time.now,TCPSocket.open(remote_host.delete("[]"),remote_port)]
                    conn[1].setsockopt(Socket::SOL_SOCKET, Socket::SO_KEEPALIVE, true)
                    @@connections[conn_id]=conn
                    $stderr.puts "[#{conn_id}] Connected to #{remote_host}:#{remote_port} #{conn[1]}"
                    res.status=201 # Created
                else
                    res.status=409 # Conflict
                end
            rescue Errno::EMFILE
                $stderr.puts "[#{conn_id}] Connection failed: #$!"
                @@connections.delete_if do |conn_id, conn|
                    conn[1].close if not conn[1].closed?
                    $stderr.puts "[#{conn_id}] Connection closed for #{conn_id}=#{conn[1]}"
                    true
                end
                res['Content-Type'] = "text/plain"
                res.body=$!.message
                res.status=503 # Service Unavailable
            rescue
                res['Content-Type'] = "text/plain"
                res.body=$!.message
                $stderr.puts "[#{conn_id}] Connection failed: #$!"
                res.status=406 # Not Acceptable
            end
        end

        def do_PUT(req, res)
            conn_id = req.path.split("/").last
            return if not s=get_socket(req,res)
            begin
                s.print req.body
            rescue Errno::EPIPE, IOError
                $stderr.puts "[#{conn_id}] Connection closed in remote destination (PUT)"
                close_socket(req, res)
                res.status=410 # GONE
            end
        end

        def do_GET(req, res)
            conn_id = req.path.split("/").last
            return if not conn=get_socket(req,res)
            begin
                res.body = conn.read_nonblock(MAXBUF)
            rescue IO::WaitReadable
                if IO.select([conn],nil,nil,READ_TIMEOUT-3)
                    retry
                else # Timeout
                    res.body = ''
                    res.status=204 # No Content
                end
            rescue EOFError, Errno::EPIPE, IOError
                if conn.closed?
                    $stderr.puts "[#{conn_id}] Connection closed by remote destination (GET)"
                else
                    $stderr.puts "[#{conn_id}] Connection closed (GET) #{$!}"
                end
                close_socket(req, res)
                res.status=410 # Gone
            rescue
                $stderr.puts $!.class
            end
        end

        def do_DELETE(req, res)
            t=Time.now
            @@connections.delete_if do |conn_id, conn|
                if t-conn[0] > SERVER_CONNECTION_TIMEOUT
                    conn[1].close if not conn[1].closed?
                    $stderr.puts "[#{conn_id}] Connection timed out for #{conn_id}=#{conn[1]}"
                    true
                else
                    false
                end
            end
            conn_id = req.path.split("/").last
            $stderr.puts "[#{conn_id}] Connection closed in client. Trying to close it in remote destination"
            close_socket(req, res)
            res.status=200 # OK
        end

    end

    s = WEBrick::HTTPServer.new(
        :Port            => localPort.to_i,
        :RequestTimeout  => 600
    )
    s.mount(location, BridgeServlet)
    trap("INT"){ s.shutdown }
    s.start

else # Client

    @output=Queue.new
    @output_thread=Thread.new do
        loop do
            $stderr.puts @output.pop
        end
    end
    def output_queue(mes)
        if @output_thread.alive?
            @output.push mes
        else
            until @output.empty? do
                $stderr.puts @output.pop true
            end
            $stderr.puts mes
        end
    end

    def signal_trap(sig)
        case sig
            when "INT"
                output_queue "Interrupt"
            when "TERM"
                output_queue "Terminate"
        end
        @output_thread.run until @output.empty?
        Thread.main.exit
    end

    trap("INT") { signal_trap "INT" }
    trap("TERM") { signal_trap "TERM" }
    trap("HUP") { output_queue "Hangup" }
    trap("PIPE") { output_queue "Broken pipe" }

    require "net/http"
    require 'uri'

    # HACK! https://bugs.ruby-lang.org/issues/12921
    class Net::HTTP
        def proxy_user
          if @proxy_from_env then
            proxy_uri && proxy_uri.user
          else
            @proxy_user
          end
        end
        def proxy_pass
          if @proxy_from_env then
            proxy_uri && proxy_uri.password
          else
            @proxy_pass
          end
        end
    end

    url = URI(url)
    if url.find_proxy
        output_queue "Using proxy: #{url.find_proxy}"
    end

    case localPort
    when "STDIN","-"
        _in=$stdin
        _out=$stdout
    else
        output_queue "Opening local port #{localPort}"
        local_server = Socket.new(:INET, :STREAM, 0)
        local_server.bind Addrinfo.tcp("127.0.0.1", localPort.to_i)
        local_server.listen CLIENT_PENDING_CONNECTIONS
        Thread.abort_on_exception = false
    end

    lwrr=ThreadGroup.new
    lrrw=ThreadGroup.new
    random=Random.new

loop do

    case localPort
    when "STDIN","-"
        # Keeps this unbuffered
        _in.sync=true
        _out.sync=true
    else
        output_queue "Waiting for local connection to port #{localPort}"
        local_server_conn = nil
        loop do
            if select([local_server],nil,nil,nil)
                if lwrr.list.length < CLIENT_MAX_CONNECTIONS and lrrw.list.length < CLIENT_MAX_CONNECTIONS
                    local_server_conn, addrinfo = local_server.accept
                    break
                else
                    output_queue "Too many local connections (limit #{CLIENT_MAX_CONNECTIONS})"
                    sleep 1
                end
            else
                output_queue "Still waiting for local connection to port #{localPort}"
                sleep 1
            end
        end
        local_server_conn.setsockopt Socket::Option.linger(true, 10)
        # Keep connection alive
        local_server_conn.setsockopt(Socket::SOL_SOCKET, Socket::SO_KEEPALIVE, true)
        _in=_out=local_server_conn
    end

    #unique Connection IDentifier
    uuid=random.bytes(16).unpack("NnnnnN")
    uuid[2]=(uuid[2] & 0x0fff) | 0x4000
    uuid[3]=(uuid[3] & 0x3fff) | 0x8000
    uuid=("%08x-%04x-%04x-%04x-%04x%08x" % uuid)

lrrw.add(client_thread=Thread.new(_in,_out,uuid) do |_in,_out,conn_id| begin
    output_queue "\nThread started"

    # Open the connection
    http=nil
    begin
        begin
            output_queue "Opening connection over HTTP bridge for #{remote_host}:#{remote_port} (#{conn_id})"
            # HACK! new().start() because of https://bugs.ruby-lang.org/issues/13351
            http=Net::HTTP.new(url.host.delete("[]"), url.port).start
            begin
                res = http.post("#{url.path}/#{conn_id}","#{remote_host}:#{remote_port}")
                if not res.kind_of? Net::HTTPCreated
                    output_queue "The bridge failed to connect to the remote location (#{res}): #{res.body}"
                    # Not connected, nothing more to do
                    Thread.current.exit
                end
            end
        rescue Errno::EPIPE
            output_queue "Connection to bridge #{url} closed"
            retry
        end

        # Launch Local write/Remote read loop
        lwrr.add(paired_thread=Thread.new(Thread.current) do |paired_thread|
            begin
                output_queue "Local write/Remote read loop started"
                output_queue " #{lwrr.list.length} (lw/rr) #{lrrw.list.length} (lr/rw) threads "
                Net::HTTP.new(url.host.delete("[]"), url.port).start do |http|
                    http.read_timeout=READ_TIMEOUT+3
                    while paired_thread.alive?
                        res = http.get("#{url.path}/#{conn_id}")
                        if res.kind_of? Net::HTTPOK
                            _out.print res.body
                        elsif res.kind_of? Net::HTTPGone
                            output_queue "Connection closed in remote location (lw/rr)"
                            break
                        elsif res.kind_of? Net::HTTPNotFound
                            output_queue "Connection not opened on bridge"
                            break
                        end
                    end
                end
            rescue Errno::EPIPE, IOError
                output_queue "Local connection closed (lw/rr)"
            rescue Errno::ECONNRESET
                output_queue "Connection reset (lw/rr)"
            rescue EOFError
                # retry if local connection is still open
                retry if paired_thread.alive?
                output_queue "Connection to bridge closed (lw/rr)"
            rescue Errno::ECONNREFUSED
                output_queue "Connection to bridge failed (lw/rr)"
            rescue Timeout::Error
                output_queue "Timeout (lw/rr)"
                retry if paired_thread.alive?
            rescue Net::ReadTimeout
                output_queue "Net::ReadTimeout (lw/rr)"
                retry if paired_thread.alive?
            rescue Net::HTTPServerError
                raise res.message
            ensure
                output_queue " #{lwrr.list.length-1} (lw/rr) #{lrrw.list.length} (lr/rw) threads "
            end
        end)

        # Launch "Local read/Remote write loop started"
        output_queue "Local read/Remote write loop started"
        output_queue " #{lwrr.list.length} (lw/rr) #{lrrw.list.length} (lr/rw) threads "
        # Keep buffer between retries
        buf=String.new
        begin
            begin
                while paired_thread.alive?
                    begin
                        # first read from _in ONLY if buf is empty
                        _in.read_nonblock(MAXBUF,buf) if buf.empty?
                    rescue IO::WaitReadable, Errno::EINTR
                        select([_in],nil,nil,3)
                        retry if paired_thread.alive?
                        break
                    rescue
                        output_queue "Local connection closed (lr/rw)"
                        break
                    end

                    res = http.put("#{url.path}/#{conn_id}",buf)
                    if res.kind_of? Net::HTTPGone
                        output_queue "Connection closed in remote location (lr/rw)"
                        break
                    end

                    # Buffer sent, clear it
                    buf.clear
                end
            end
        rescue Net::ReadTimeout
            output_queue "Net::ReadTimeout (lr/rw)"
            retry if paired_thread.alive?
        rescue Net::HTTPServerError
            raise "Server said: '#{res.message}'"
        rescue Errno::EPIPE, IOError
            # retry if local connection is still open
            retry if paired_thread.alive?
            output_queue "Connection to bridge closed (lr/rw)"
        end
    rescue Errno::ECONNREFUSED
        output_queue "Connection to bridge failed"
    ensure
        if http
            begin
                output_queue "Closing bridge connection to remote location"
                http.delete("#{url.path}/#{conn_id}")
            ensure
                http.finish
            end
        end
    end
    output_queue "Thread Finished!"
    ensure
        output_queue " #{lwrr.list.length} (lw/rr) #{lrrw.list.length-1} (lr/rw) threads "
        # close only here nowhere else to avoid segmentation fault
        _in.close if not _in.closed?
        # https://bugs.ruby-lang.org/issues/13076
    end
end)
    case localPort
    when "STDIN","-"
        client_thread.join
        break
    end
end
output_queue "\n"
@output_thread.run until @output.empty?
end

$stderr.puts "Program Finished!"
